set["couchdb_lucene"]["tmp_dir"]     = '/tmp'
set["couchdb_lucene"]["install_dir"] = '/usr/share/couchdb-lucene-0.9.0'
set["couchdb_lucene"]["couchdb_local_ini_path"] = '/etc/couchdb/local.ini'
set["couchdb_lucene"]["release_commit"] = '3565b0acbf03d86c91d174f431c09b60961e63b1'
set["couchdb_lucene"]["deb_file"] = 'http://nexus.motechproject.org/content/repositories/releases/com/github/rnewson/couchdb/lucene/couchdb-lucene/0.9.0/couchdb-lucene-0.9.0.deb'
